

/**
 * DO NOT EDIT THIS FILE
 */

//
#include "./Chat.hpp"


//
#include <iostream>
#include <string>


//
using CPSC351::Chat;
using std::cout, std::cin, std::endl;
using std::string;


//
int main(int argc, char* argv[])
{
	//
	if ( argc != 4 ) {
		throw std::runtime_error("Please specify the listening port as the first argument, the outgoing hostname as the second, and the outgoing port as the third.");
	}
	
	//
	int port_listen = Chat::INVALID_PORT;
	std::string hostname;
	int port_out = Chat::INVALID_PORT;
	try
	{
		port_listen = atoi(argv[1]);
		hostname = argv[2];
		port_out = atoi(argv[3]);
	}
	catch( ... )
	{
		cout << "Failed to parse hostname/ports, for some reason" << endl;
		return 1;
	}
	
	//
	{
		Chat chat(port_listen, hostname, port_out);
		chat.run();
	}
	
	//
	cout << "Program exiting ..." << endl;
	
	return 0;
}










